F........F..FF.E......S........FFFF....................E.........
======================================================================
ERROR: test suite for <class 'tempest.api.compute.servers.test_servers_negative.ServersNegativeTestJSON'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/imkarrer/jumpgate_env/local/lib/python2.7/site-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/home/imkarrer/jumpgate_env/local/lib/python2.7/site-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/home/imkarrer/jumpgate_env/local/lib/python2.7/site-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/home/imkarrer/jumpgate_env/local/lib/python2.7/site-packages/nose/util.py", line 470, in try_run
    return func()
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/api/compute/servers/test_servers_negative.py", line 51, in setUpClass
    cls.alt_os = clients.AltManager()
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/clients.py", line 420, in __init__
    credentials=auth.get_default_credentials('alt_user'),
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/auth.py", line 466, in get_default_credentials
    return get_credentials(fill_in=fill_in, credential_type=credential_type)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/auth.py", line 496, in get_credentials
    creds = credential_class.get_default(credential_type)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/auth.py", line 582, in get_default
    raise exceptions.InvalidConfiguration()
InvalidConfiguration: Invalid Configuration
-------------------- >> begin captured logging << --------------------
tempest.common.rest_client: INFO: Request (ServersTestJSON:tearDownClass): 204 DELETE http://localhost:5000/compute/v2/333582/servers/5427662 1.737s
tempest.common.rest_client: INFO: Request (ServersTestJSON:tearDownClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.719s
tempest.common.rest_client: INFO: Request (ServersTestJSON:tearDownClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.734s
tempest.common.rest_client: INFO: Request (ServersTestJSON:tearDownClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.764s
tempest.common.rest_client: INFO: Request (ServersTestJSON:tearDownClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.745s
tempest.common.rest_client: INFO: Request (ServersTestJSON:tearDownClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.785s
tempest.common.rest_client: INFO: Request (ServersTestJSON:tearDownClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.728s
tempest.common.rest_client: INFO: Request (ServersTestJSON:tearDownClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.730s
tempest.common.rest_client: INFO: Request (ServersTestJSON:tearDownClass): 404 GET http://localhost:5000/compute/v2/333582/servers/5427662 1.852s
tempest.common.rest_client: INFO: Request (ServersNegativeTestJSON:setUpClass): 200 POST http://127.0.0.1:5000/v2.0/tokens
tempest.common.rest_client: INFO: Request (ServersNegativeTestJSON:setUpClass): 200 POST http://127.0.0.1:5000/v2.0/tokens
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: tempest.api.compute.images.test_list_images.ListImagesTestJSON.create_test_server_group
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{2014-07-14 16:02:02,266 26175 INFO     [tempest.common.rest_client] Request (main): 501 POST http://localhost:5000/compute/v2/333582/os-server-groups 0.011s}}}

Traceback (most recent call last):
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/api/compute/base.py", line 274, in create_test_server_group
    resp, body = cls.servers_client.create_server_group(name, policy)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/services/compute/json/servers_client.py", line 512, in create_server_group
    resp, body = self.post('os-server-groups', post_body)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/common/rest_client.py", line 218, in post
    return self.request('POST', url, extra_headers, headers, body)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/common/rest_client.py", line 430, in request
    resp, resp_body)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/common/rest_client.py", line 526, in _error_checker
    raise exceptions.ServerFault(message)
ServerFault: Got server fault
Details: Not Implemented

-------------------- >> begin captured logging << --------------------
tempest.common.rest_client: INFO: Request (main): 501 POST http://localhost:5000/compute/v2/333582/os-server-groups 0.011s
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.compute.test_extensions.ExtensionsTestJSON.test_list_extensions[gate]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{
2014-07-14 15:00:41,784 26175 INFO     [tempest.common.rest_client] Request (ExtensionsTestJSON:test_list_extensions): 200 POST http://127.0.0.1:5000/v2.0/tokens
2014-07-14 15:00:41,839 26175 INFO     [tempest.common.rest_client] Request (ExtensionsTestJSON:test_list_extensions): 200 GET http://localhost:5000/compute/v2/333582/extensions 0.051s
}}}

Traceback (most recent call last):
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/api/compute/test_extensions.py", line 39, in test_list_extensions
    self.assertIn('Hosts', map(lambda x: x['name'], extensions))
  File "/home/imkarrer/jumpgate_env/local/lib/python2.7/site-packages/testtools/testcase.py", line 327, in assertIn
    self.assertThat(haystack, Contains(needle))
  File "/home/imkarrer/jumpgate_env/local/lib/python2.7/site-packages/testtools/testcase.py", line 406, in assertThat
    raise mismatch_error
MismatchError: 'Hosts' not in [u'AvailabilityZone']

-------------------- >> begin captured logging << --------------------
tempest.common.rest_client: INFO: Request (ExtensionsTestJSON:test_list_extensions): 200 POST http://127.0.0.1:5000/v2.0/tokens
tempest.common.rest_client: INFO: Request (ExtensionsTestJSON:test_list_extensions): 200 GET http://localhost:5000/compute/v2/333582/extensions 0.051s
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.compute.keypairs.test_keypairs.KeyPairsV2TestJSON.test_keypair_create_with_pub_key[gate]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{
2014-07-14 15:00:55,250 26175 INFO     [tempest.common.rest_client] Request (KeyPairsV2TestJSON:test_keypair_create_with_pub_key): 200 POST http://127.0.0.1:5000/v2.0/tokens
2014-07-14 15:00:56,831 26175 INFO     [tempest.common.rest_client] Request (KeyPairsV2TestJSON:test_keypair_create_with_pub_key): 409 POST http://localhost:5000/compute/v2/333582/os-keypairs 1.578s
}}}

Traceback (most recent call last):
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/api/compute/keypairs/test_keypairs.py", line 109, in test_keypair_create_with_pub_key
    resp, keypair = self._create_keypair(k_name, pub_key)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/api/compute/keypairs/test_keypairs.py", line 34, in _create_keypair
    resp, body = self.client.create_keypair(keypair_name, pub_key)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/services/compute/json/keypairs_client.py", line 54, in create_keypair
    resp, body = self.post("os-keypairs", body=post_body)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/common/rest_client.py", line 218, in post
    return self.request('POST', url, extra_headers, headers, body)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/common/rest_client.py", line 430, in request
    resp, resp_body)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/common/rest_client.py", line 484, in _error_checker
    raise exceptions.Conflict(resp_body)
Conflict: An object with that identifier already exists
Details: {u'message': u'SSH key already exists.', u'code': u'409'}

-------------------- >> begin captured logging << --------------------
tempest.common.rest_client: INFO: Request (KeyPairsV2TestJSON:setUpClass): 200 POST http://127.0.0.1:5000/v2.0/tokens
tempest.common.rest_client: INFO: Request (KeyPairsV2TestJSON:setUpClass): 200 POST http://127.0.0.1:5000/v2.0/tokens
tempest.common.rest_client: INFO: Request (KeyPairsV2TestJSON:test_keypair_create_with_pub_key): 200 POST http://127.0.0.1:5000/v2.0/tokens
tempest.common.rest_client: INFO: Request (KeyPairsV2TestJSON:test_keypair_create_with_pub_key): 409 POST http://localhost:5000/compute/v2/333582/os-keypairs 1.578s
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.compute.admin.test_availability_zone.AZAdminV2TestJSON.test_get_availability_zone_list_detail[gate]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{2014-07-14 15:01:09,693 26175 INFO     [tempest.common.rest_client] Request (AZAdminV2TestJSON:test_get_availability_zone_list_detail): 200 GET http://localhost:5000/compute/v2/333582/os-availability-zone/detail 1.747s}}}

Traceback (most recent call last):
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/api/compute/admin/test_availability_zone.py", line 42, in test_get_availability_zone_list_detail
    self.client.get_availability_zone_list_detail()
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/services/compute/json/availability_zone_client.py", line 42, in get_availability_zone_list_detail
    body)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/common/rest_client.py", line 578, in validate_response
    raise exceptions.InvalidHTTPResponseBody(msg)
InvalidHTTPResponseBody: HTTP response body is invalid json or xml
Details: HTTP response body is invalid (None is not of type 'object'

Failed validating 'type' in schema['properties']['availabilityZoneInfo']['items']['properties']['hosts']:
    {'patternProperties': {'^[a-zA-Z0-9-_.]+$': {'patternProperties': {'^.*$': {'properties': {'active': {'type': 'boolean'},
                                                                                               'available': {'type': 'boolean'},
                                                                                               'updated_at': {'type': 'string'}},
                                                                                'required': ['available',
                                                                                             'active',
                                                                                             'updated_at'],
                                                                                'type': 'object'}},
                                                 'type': 'object'}},
     'type': 'object'}

On instance['availabilityZoneInfo'][0]['hosts']:
    None)

-------------------- >> begin captured logging << --------------------
tempest.common.rest_client: INFO: Request (AZAdminV2TestJSON:test_get_availability_zone_list_detail): 200 GET http://localhost:5000/compute/v2/333582/os-availability-zone/detail 1.747s
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.compute.servers.test_create_server.ServersTestJSON.test_list_servers[gate,smoke]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{2014-07-14 15:04:06,693 26175 INFO     [tempest.common.rest_client] Request (ServersTestJSON:test_list_servers): 200 GET http://localhost:5000/compute/v2/333582/servers 3.405s}}}

Traceback (most recent call last):
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/api/compute/servers/test_create_server.py", line 72, in test_list_servers
    resp, body = self.client.list_servers()
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/services/compute/json/servers_client.py", line 155, in list_servers
    self.validate_response(common_schema.list_servers, resp, body)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/common/rest_client.py", line 578, in validate_response
    raise exceptions.InvalidHTTPResponseBody(msg)
InvalidHTTPResponseBody: HTTP response body is invalid json or xml
Details: HTTP response body is invalid (4846014 is not of type 'string'

Failed validating 'type' in schema['properties']['servers']['items']['properties']['id']:
    {'type': 'string'}

On instance['servers'][0]['id']:
    4846014)

-------------------- >> begin captured logging << --------------------
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 POST http://127.0.0.1:5000/v2.0/tokens
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 POST http://127.0.0.1:5000/v2.0/tokens
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 POST http://127.0.0.1:5000/v2.0/tokens
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 202 POST http://localhost:5000/compute/v2/333582/servers 2.977s
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.928s
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.747s
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.762s
tempest.common.waiters: INFO: State transition "SHUTOFF/None" ==> "SHUTOFF/ASSIGN_HOST" after 22 second wait
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.825s
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.776s
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 3.771s
tempest.common.waiters: INFO: State transition "SHUTOFF/ASSIGN_HOST" ==> "SHUTOFF/CLONE_CLOUD_TEMPLATE" after 58 second wait
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.984s
tempest.common.waiters: INFO: State transition "SHUTOFF/CLONE_CLOUD_TEMPLATE" ==> "SHUTOFF/CHECK_CLOUD_DISK_TEMPLATE_TRANSFER" after 69 second wait
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.847s
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.783s
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.866s
tempest.common.waiters: INFO: State transition "SHUTOFF/CHECK_CLOUD_DISK_TEMPLATE_TRANSFER" ==> "SHUTOFF/ATTACH_PRIMARY_DISK" after 101 second wait
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.791s
tempest.common.waiters: INFO: State transition "SHUTOFF/ATTACH_PRIMARY_DISK" ==> "SHUTOFF/CLOUD_PROVISION_SETUP" after 112 second wait
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.766s
tempest.common.waiters: INFO: State transition "SHUTOFF/CLOUD_PROVISION_SETUP" ==> "SHUTOFF/POWER_ON" after 123 second wait
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.811s
tempest.common.waiters: INFO: State transition "SHUTOFF/POWER_ON" ==> "BUILD/POWER_ON" after 134 second wait
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.915s
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 1.236s
tempest.common.waiters: INFO: State transition "BUILD/POWER_ON" ==> "BUILD/START_SERVICE_SETUP" after 156 second wait
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 1.002s
tempest.common.waiters: INFO: State transition "BUILD/START_SERVICE_SETUP" ==> "ACTIVE/None" after 167 second wait
tempest.common.rest_client: INFO: Request (ServersTestJSON:setUpClass): 200 GET http://localhost:5000/compute/v2/333582/servers/5427662 0.743s
tempest.common.rest_client: INFO: Request (ServersTestJSON:test_list_servers): 200 GET http://localhost:5000/compute/v2/333582/servers 3.405s
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.compute.servers.test_list_server_filters.ListServerFiltersTestJSON.test_list_servers_filter_by_limit[gate]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{2014-07-14 15:53:40,073 26175 INFO     [tempest.common.rest_client] Request (ListServerFiltersTestJSON:test_list_servers_filter_by_limit): 200 GET http://localhost:5000/compute/v2/333582/servers?limit=1 0.877s}}}

Traceback (most recent call last):
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/api/compute/servers/test_list_server_filters.py", line 146, in test_list_servers_filter_by_limit
    resp, servers = self.client.list_servers(params)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/services/compute/json/servers_client.py", line 155, in list_servers
    self.validate_response(common_schema.list_servers, resp, body)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/common/rest_client.py", line 578, in validate_response
    raise exceptions.InvalidHTTPResponseBody(msg)
InvalidHTTPResponseBody: HTTP response body is invalid json or xml
Details: HTTP response body is invalid (4846014 is not of type 'string'

Failed validating 'type' in schema['properties']['servers']['items']['properties']['id']:
    {'type': 'string'}

On instance['servers'][0]['id']:
    4846014)

-------------------- >> begin captured logging << --------------------
tempest.common.rest_client: INFO: Request (ListServerFiltersTestJSON:test_list_servers_filter_by_limit): 200 GET http://localhost:5000/compute/v2/333582/servers?limit=1 0.877s
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.compute.servers.test_list_server_filters.ListServerFiltersTestJSON.test_list_servers_filter_by_server_name[gate]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{2014-07-14 15:53:41,001 26175 INFO     [tempest.common.rest_client] Request (ListServerFiltersTestJSON:test_list_servers_filter_by_server_name): 200 GET http://localhost:5000/compute/v2/333582/servers?name=ListServerFiltersTestJSON-instance-423106231 0.919s}}}

Traceback (most recent call last):
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/api/compute/servers/test_list_server_filters.py", line 107, in test_list_servers_filter_by_server_name
    resp, body = self.client.list_servers(params)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/services/compute/json/servers_client.py", line 155, in list_servers
    self.validate_response(common_schema.list_servers, resp, body)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/common/rest_client.py", line 578, in validate_response
    raise exceptions.InvalidHTTPResponseBody(msg)
InvalidHTTPResponseBody: HTTP response body is invalid json or xml
Details: HTTP response body is invalid (5427978 is not of type 'string'

Failed validating 'type' in schema['properties']['servers']['items']['properties']['id']:
    {'type': 'string'}

On instance['servers'][0]['id']:
    5427978)

-------------------- >> begin captured logging << --------------------
tempest.common.rest_client: INFO: Request (ListServerFiltersTestJSON:test_list_servers_filter_by_server_name): 200 GET http://localhost:5000/compute/v2/333582/servers?name=ListServerFiltersTestJSON-instance-423106231 0.919s
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.compute.servers.test_list_server_filters.ListServerFiltersTestJSON.test_list_servers_filtered_by_name_wildcard[gate]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{2014-07-14 15:53:42,284 26175 INFO     [tempest.common.rest_client] Request (ListServerFiltersTestJSON:test_list_servers_filtered_by_name_wildcard): 200 GET http://localhost:5000/compute/v2/333582/servers?name=-instance 1.265s}}}

Traceback (most recent call last):
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/api/compute/servers/test_list_server_filters.py", line 216, in test_list_servers_filtered_by_name_wildcard
    resp, body = self.client.list_servers(params)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/services/compute/json/servers_client.py", line 155, in list_servers
    self.validate_response(common_schema.list_servers, resp, body)
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/common/rest_client.py", line 578, in validate_response
    raise exceptions.InvalidHTTPResponseBody(msg)
InvalidHTTPResponseBody: HTTP response body is invalid json or xml
Details: HTTP response body is invalid (5427622 is not of type 'string'

Failed validating 'type' in schema['properties']['servers']['items']['properties']['id']:
    {'type': 'string'}

On instance['servers'][0]['id']:
    5427622)

-------------------- >> begin captured logging << --------------------
tempest.common.rest_client: INFO: Request (ListServerFiltersTestJSON:test_list_servers_filtered_by_name_wildcard): 200 GET http://localhost:5000/compute/v2/333582/servers?name=-instance 1.265s
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: tempest.api.compute.servers.test_list_server_filters.ListServerFiltersTestJSON.test_list_servers_filtered_by_ip[gate]
----------------------------------------------------------------------
_StringException: pythonlogging:'': {{{
2014-07-14 15:53:43,082 26175 INFO     [tempest.common.rest_client] Request (ListServerFiltersTestJSON:test_list_servers_filtered_by_ip): 200 GET http://localhost:5000/compute/v2/333582/servers/5427978 0.777s
2014-07-14 15:53:44,109 26175 INFO     [tempest.common.rest_client] Request (ListServerFiltersTestJSON:test_list_servers_filtered_by_ip): 200 GET http://localhost:5000/compute/v2/333582/servers?ip=10.91.21.250 1.013s
}}}

Traceback (most recent call last):
  File "/home/imkarrer/git_jumpgate/jumpgate/tempest/tempest/api/compute/servers/test_list_server_filters.py", line 244, in test_list_servers_filtered_by_ip
    self.assertIn(self.s1_name, map(lambda x: x['name'], servers))
  File "/home/imkarrer/jumpgate_env/local/lib/python2.7/site-packages/testtools/testcase.py", line 327, in assertIn
    self.assertThat(haystack, Contains(needle))
  File "/home/imkarrer/jumpgate_env/local/lib/python2.7/site-packages/testtools/testcase.py", line 406, in assertThat
    raise mismatch_error
MismatchError: 'ListServerFiltersTestJSON-instance-423106231' not in []

-------------------- >> begin captured logging << --------------------
tempest.common.rest_client: INFO: Request (ListServerFiltersTestJSON:test_list_servers_filtered_by_ip): 200 GET http://localhost:5000/compute/v2/333582/servers/5427978 0.777s
tempest.common.rest_client: INFO: Request (ListServerFiltersTestJSON:test_list_servers_filtered_by_ip): 200 GET http://localhost:5000/compute/v2/333582/servers?ip=10.91.21.250 1.013s
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 64 tests in 5047.007s

FAILED (SKIP=1, errors=2, failures=8)
